// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"mall/service/user/rpc/internal/logic"
	"mall/service/user/rpc/internal/svc"
	"mall/service/user/rpc/proto3"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	proto3.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *proto3.LoginRequest) (*proto3.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *proto3.RegisterRequest) (*proto3.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *proto3.UserInfoRequest) (*proto3.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
