Name: Product
Host: 0.0.0.0
Port: 8001

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: product.rpc

Prometheus:
  Host: 0.0.0.0
  Port: 10081
  Path: /metrics

Telemetry:
  Name: product.api
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger