Name: product.rpc
ListenOn: 127.0.0.1:9001

Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: 127.0.0.1:6379
  Type: node # node可以不写，可以设为cluster
  # Pass: xxx # 如果有密码

Prometheus:
  Host: 0.0.0.0
  Port: 10091
  Path: /metrics

Telemetry:
  Name: product.rpc
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger