// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"mall/service/order/rpc/internal/logic"
	"mall/service/order/rpc/internal/svc"
	"mall/service/order/rpc/proto3"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	proto3.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Create(ctx context.Context, in *proto3.CreateRequest) (*proto3.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *OrderServer) Update(ctx context.Context, in *proto3.UpdateRequest) (*proto3.UpdateResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *OrderServer) Remove(ctx context.Context, in *proto3.RemoveRequest) (*proto3.RemoveResponse, error) {
	l := logic.NewRemoveLogic(ctx, s.svcCtx)
	return l.Remove(in)
}

func (s *OrderServer) Detail(ctx context.Context, in *proto3.DetailRequest) (*proto3.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *OrderServer) List(ctx context.Context, in *proto3.ListRequest) (*proto3.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *OrderServer) Paid(ctx context.Context, in *proto3.PaidRequest) (*proto3.PaidResponse, error) {
	l := logic.NewPaidLogic(ctx, s.svcCtx)
	return l.Paid(in)
}

func (s *OrderServer) CreateRevert(ctx context.Context, in *proto3.CreateRequest) (*proto3.CreateResponse, error) {
	l := logic.NewCreateRevertLogic(ctx, s.svcCtx)
	return l.CreateRevert(in)
}

func (s *OrderServer) GetUserLatest(ctx context.Context, in *proto3.GetUserLatestRequest) (*proto3.GetUserLatestResponse, error) {
	l := logic.NewGetUserLatestLogic(ctx, s.svcCtx)
	return l.GetUserLatest(in)
}
